/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'SimulateSignal': ApiRouteHandler<{ type: 'demand_surge' | 'competitor_price' | 'stock_drop'; value: number; reason?: string }, unknown, { topic: 'market.signal'; data: { type: 'demand_surge' | 'competitor_price' | 'stock_drop'; value: number; reason?: string; timestamp: string; source: string } }>
    'PricingAgent': EventHandler<{ type: 'demand_surge' | 'competitor_price' | 'stock_drop'; value: number; reason?: string; timestamp: string; source: string }, never>
  }
    
}